# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
default_packages:
  - tar
  - git
  - vim
  - wget
  - curl
  - unzip
  - python39
  - python3-pip
  - python3-setuptools
  - python3-virtualenv
  - libcgroup-tools
