# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_playbook: system.yml

- import_playbook: tdp_manager_install.yml

- import_playbook: tdp_collections_install.yml

- import_playbook: tdp_collections_config.yml

- import_playbook: tdp_manager_config.yml

- import_playbook: tdp_manager_init.yml

- import_playbook: tdp_collections_init.yml

- import_playbook: tdp_manager_start.yml
